BUILD: quic: Move a ASSUME_NONNULL() for variable which is not null
Some new compilers warn that <oldest_lost> variable can be null even this
cannot be the case as mentioned by the comment about an already present
ASSUME_NONNULL() call comment.

src/quic_loss.c: In function ‘qc_release_lost_pkts’:
src/quic_loss.c:307:86: error: potential null pointer dereference [-Werror=null-dereference]
  307 |   unsigned int period = newest_lost->time_sent_ms - oldest_lost->time_sent_ms;
      |                                                     ~~~~~~~~~~~^~~~~~~~~~~~~~

Move up this ASSUME_NONNULL() statement to please these compiler.

Must be backported as far as 2.6.